serve multiple cores from an lss node

diff --git a/templates/profile/hathitrust/solr_lss/index-release-lss.sh.erb b/templates/profile/hathitrust/solr_lss/index-release-lss.sh.erb
--- a/templates/profile/hathitrust/solr_lss/index-release-lss.sh.erb
+++ b/templates/profile/hathitrust/solr_lss/index-release-lss.sh.erb
@@ -3,23 +3,27 @@
 TODAY=`date +%Y-%m-%d`
 #TODAY="2019-08-31"
 
-SYMLINK=/htsolr/current_snap
-TARGET=/htsolr/lss/.snapshot/<%= @snapshot_name %>_${TODAY}
+BASE=/htsolr/lss
+SYMLINKBASE=/htsolr/serve
+SNAP=".snapshot/<%= @snapshot_name %>_${TODAY}"
+CORES="<%= @solr_cores.join(' ') %>"
 
 # check if the administrative LSS release stop flag is set
-if [ -f /htsolr/lss/flags/STOPLSSRELEASE ]; then
+if [ -f ${BASE}/flags/STOPLSSRELEASE ]; then
   /bin/echo "LSS release stop flag present...skip release today"
   exit 1
 fi
 
 # check that today's snap exists
-if [ ! -d ${TARGET} ]; then
-  /bin/echo "missing today's snapshot...aborting release"
-  exit 1
-fi
+for s in $CORES; do
+  if [ ! -d $BASE/cores/${s}/${SNAP} ]; then
+    /bin/echo "missing today's snapshot...aborting release"
+    exit 1
+  fi
+done
 
 # check todays snap for 'busy' flag
-if [ -f ${TARGET}/flags/busy ]; then
+if [ -f $BASE/flags/${SNAP}/busy ]; then
   /bin/echo "indexing and/or optimization ocurring on a shard...skip release today"
   exit 1
 fi
@@ -30,11 +34,13 @@ fi
 <% if not @is_primary_site %>#<% end %>  exit 1
 <% if not @is_primary_site %>#<% end %>fi
 
-SEGMENTS=`ls ${TARGET}/cores/<%= @solr_core %>/core-<%= @solr_core %>x/data/index/*.fdt | wc -l`
-if [ ${SEGMENTS} -lt 1 ] || [ ${SEGMENTS} -gt 2 ]; then
-  /bin/echo "at least one core served by `hostname -s` has an improper number of segments...aborting release"
-  exit 1
-fi
+for s in $CORES; do
+  SEGMENTS=`ls ${BASE}/cores/${s}/${SNAP}/core-${s}x/data/index/*.fdt | wc -l`
+  if [ ${SEGMENTS} -lt 1 ] || [ ${SEGMENTS} -gt 2 ]; then
+    /bin/echo "at least one core served by `hostname -s` has an improper number of segments...aborting release"
+    exit 1
+  fi
+done
 
 # stop solr
 systemctl stop solr
@@ -43,12 +49,19 @@ if [ $? -ne 0 ]; then
   exit 1
 fi
 
-# replace the snapshot symlink
-rm -f ${SYMLINK} && ln -s ${TARGET} ${SYMLINK}
+# replace the snapshot symlinks
+rm -f ${SYMLINKBASE}/lss-shared && ln -s ${BASE}/shared/${SNAP} ${SYMLINKBASE}/lss-shared
 if [ $? -ne 0 ]; then
-    /bin/echo "error removing or creating ${SYMLINK} symlink...solr WILL NOT be started on `hostname -s`"
+    /bin/echo "error removing or creating /htsolr/serve/lss-shared symlink...solr-current-lss WILL NOT be started on `hostname -s`"
     exit 1
 fi
+for s in ${CORES}; do
+  rm -f ${SYMLINKBASE}/lss-${s} && ln -s ${BASE}/cores/${s}/${SNAP} ${SYMLINKBASE}/lss-${s}
+  if [ $? -ne 0 ]; then
+    /bin/echo "error removing or creating symlink for core ${s}...solr-current-lss WILL NOT be started on `hostname -s`"
+    exit 1
+  fi
+done
 
 # if all went well, start solr
 systemctl start solr
@@ -63,19 +76,21 @@ fi
 
 # run the first query to initialize solr
 INITQUERY=0
-sleep 5
-if ! wget -q -T 60 -t 5 -O - "http://solr-sdr-search-<%= @solr_core %>:8081/solr/core-<%= @solr_core %>x/select/?q=aardvark&version=2.2&start=0&rows=10&indent=on" >& /dev/null; then
-  /bin/echo "WARN: failed to perform initial query against core <%= @solr_core %>x after successful release"
-  INITQUERY=1
-fi
-if ! wget -q -T 60 -t 5 -O - "http://solr-sdr-search-<%= @solr_core %>:8081/solr/core-<%= @solr_core %>y/select?indent=on&q=*:*&rows=0" >& /dev/null; then
-  /bin/echo "WARN: failed to perform initial query against core <%= @solr_core %>y after successful release"
-  INITQUERY=1
-fi
+for s in $CORES; do
+  sleep 5
+  if ! wget -q -T 60 -t 5 -O - "http://solr-sdr-search-${s}:8081/solr/core-${s}x/select/?q=aardvark&version=2.2&start=0&rows=10&indent=on" >& /dev/null; then
+    /bin/echo "WARN: failed to perform initial query against core ${s}x after successful release"
+    INITQUERY=1
+  fi
+  if ! wget -q -T 60 -t 5 -O - "http://solr-sdr-search-${s}:8081/solr/core-${s}y/select?indent=on&q=*:*&rows=0" >& /dev/null; then
+    /bin/echo "WARN: failed to perform initial query against core ${s}y after successful release"
+    INITQUERY=1
+  fi
+done
 
 <% if not @is_primary_node %>#<% end %># cache warming, after delay to avoid racing with other nodes
 <% if not @is_primary_node %>#<% end %>sleep 30
-<% if not @is_primary_node %>#<% end %>/usr/bin/wget -nv -i /htsolr/lss/prep/cacheWarm169Common.txt -O - 2>/tmp/cache-warming-lss.log 1>/dev/null
+<% if not @is_primary_node %>#<% end %>/usr/bin/wget -nv -i ${BASE}/prep/cacheWarm169Common.txt -O - 2>/tmp/cache-warming-lss.log 1>/dev/null
 <% if not @is_primary_node %>#<% end %>rm -f /htapps/babel/flags/web/NEWlss-warming-*
 <% if not @is_primary_node %>#<% end %>touch /htapps/babel/flags/web/NEWlss-warming-${TODAY}
 
